version: 2.1

parameters:
  # This parameter is used to trigger the main workflow
    trigger:
        type: boolean
        default: true
  
    requirements:
        type: boolean
        default: false

jobs:
    # trigger-workflows:
    #     docker:
    #         - image: circleci/python:3.6
    #     steps:
    #     - checkout
    #     - run:
    #         name: Trigger workflows
    #         command: chmod +x .circleci/commit_check.sh && .circleci/commit_check.sh

    build-deps:
        docker:
            - image: circleci/python:3.6
        steps:
            - checkout
            - run:
                name: build-deps
                command: chmod +x .circleci/commit_check.sh && .circleci/commit_check.sh
            - persist_to_workspace:
                  root: /
                  paths:
                      - .circleci/commit_check.sh
    build_img:
        parameters:
        docker:
            - image: circleci/python:3.6
            #   aws_auth:
            #       aws_access_key_id: $AWS_ACCESS_KEY
            #       aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
        steps:
            - checkout
            - setup_remote_docker:
                version: 18.06.0-ce
            - run:
                name: Build and push wing/api-audit
                command: |
                    pip install awscli --upgrade --user
                    aws configure set \
                    aws_access_key_id $AWS_ACCESS_KEY
                    aws configure set \
                    aws_secret_access_key $AWS_SECRET_ACCESS_KEY
                    chmod +x .circleci/build_img.sh && .circleci/build_img.sh 

                    
workflows:
  version: 2
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows
  others:
    when: << pipeline.parameters.requirements >>
    jobs:
      - build_img:
            filters:
                branches:
                    only:
                        - master
