version: 2.0

jobs:
    build-deps:
        docker:
            - image: circleci/python:3.6
        steps:
            - checkout
            - run:
                name: build-deps
                command: chmod +x .circleci/commit_check.sh && .circleci/commit_check.sh
            - persist_to_workspace:
                  root: .circleci
                  paths:
                      - ./*
    build_img:
        parameters:
        docker:
            - image: circleci/python:3.6
        steps:
            - checkout
            - setup_remote_docker:
                version: 18.06.0-ce
            - attach_workspace: 
                at: .circleci
            - run:
                name: Build and push wing/api-audit
                command: |
                    pip install awscli --upgrade --user
                    aws configure set \
                    aws_access_key_id $AWS_ACCESS_KEY
                    aws configure set \
                    aws_secret_access_key $AWS_SECRET_ACCESS_KEY
                    chmod +x .circleci/build_img.sh && .circleci/build_img.sh 

                    
workflows:
  version: 2
  flow:
    jobs:
      - build-deps
      - build_img:
            requires:
                - build-deps
            filters:
                branches:
                    only:
                        - master
