version: 2

parameters:
  # This parameter is used to trigger the main workflow
  trigger:
    type: boolean
    default: true

jobs:
    trigger-workflows:
        docker:
            - image: circleci/python:3.6
        steps:
        - checkout
        - run:
            name: Trigger workflows
            command: chmod +x .circleci/commit_check.sh && .circleci/commit_check.sh

    build:
        docker:
            - image: circleci/python:3.6
        steps:
            - checkout
            - run:
                name: Check commit
                command: |
                    echo "Build step run"
                    
workflows:
  version: 2
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows
  default-workflow:
    jobs:
    - commit_check
    - build:
        requires:
            - commit_check
        filters:
            branches:
                only:
                    - master