version: 2.1

parameters:
  # This parameter is used to trigger the main workflow
    trigger:
        type: boolean
        default: true
  
    SimpleApp:
        type: boolean
        default: false

jobs:
    trigger-workflows:
        docker:
            - image: circleci/python:3.6
        steps:
        - checkout
        - run:
            name: Trigger workflows
            command: chmod +x .circleci/commit_check.sh && .circleci/commit_check.sh

    build:
        parameters:
            package_name:
                type: string
        working_directory: ~/project/packages/<< parameters.package_name >>
        docker:
            - image: circleci/python:3.6
        steps:
            - checkout
            - run:
                name: Check commit
                command: |
                    echo "Build step run"
            - persist_to_workspace:
                root: ~/project
                paths:
                    - packages/<< parameters.package_name >>
                    
workflows:
  version: 2
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows
  default-workflow:
    when: << pipeline.parameters.SimpleApp >>
    jobs:
    - build:
        filters:
            branches:
                only:
                    - master