version: 2.1

parameters:
  # This parameter is used to trigger the main workflow
  trigger:
    type: boolean
    default: true
  requirements:
    type: boolean
    default: false
jobs:
  trigger-workflows:
    docker:
      - image: circleci/python:3.6
    steps:
    - checkout
    - run:
        name: Trigger workflows
        command: chmod +x .circleci/commit_check.sh && .circleci/commit_check.sh
  build_test:
    docker:
      - image: 267120416279.dkr.ecr.us-east-1.amazonaws.com/wingaudit/api-test:2020022002
        aws_auth:
            aws_access_key_id: $AWS_ACCESS_KEY
            aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
        environment:
            TZ: "/usr/share/zoneinfo/America/New_York"
            ENV: test
            DATABASE_URL: postgresql://wingaudit@localhost/db_test?sslmode=disable
      - image: circleci/postgres:11.5-alpine-ram
        environment:
            POSTGRES_USER: wingaudit
            POSTGRES_DB: db_test
            POSTGRES_PASSWORD: ""
    working_directory: /srv/wingaudit
    steps:
      - checkout
      - run:
          name: Check tested commits
          command: |
            .circleci/sum-tests.sh > .thistest
            cat .thistest
      - restore_cache:
          key: v1-tested-commits-{{ checksum ".thistest" }}
      - run:
          name: Run tests
          command: |
            .circleci/check-tests.sh .thistest .lasttest && exit 0
            source /srv/.env/bin/activate
            nose2 --with-coverage --coverage=src tests
      - run:
          name: Save tested commits
          command: |
            cp -vf .thistest .lasttest
            cat .lasttest
      - save_cache:
          key: v1-tested-commits-{{ checksum ".lasttest" }}
          paths:
            - /srv/wingaudit/.lasttest
            - /srv/wingaudit/codecov.xml
  build_img:
    docker:
      - image: 267120416279.dkr.ecr.us-east-1.amazonaws.com/circleci/python:3.7
        aws_auth:
            aws_access_key_id: $AWS_ACCESS_KEY
            aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
        environment:
            TZ: "/usr/share/zoneinfo/America/New_York"
            VERSION_BRANCHES: "develop staging master"
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Build and push wing/api-audit
          command: |
            aws configure set \
            aws_access_key_id $AWS_ACCESS_KEY
            aws configure set \
            aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set region $AWS_DEFAULT_REGION
            .circleci/build_img.sh microservice \
            $CIRCLE_BRANCH ${CIRCLE_SHA1:0:7} \
            2020022002
      - add_ssh_keys:
          fingerprints:
            - "f3:ad:d9:6d:e9:ae:a5:9a:77:7a:6c:b5:47:9a:1c:72"
            - "48:54:db:bc:e6:3d:5e:c7:df:c6:18:11:05:e2:64:4c"
      - run:
          name: Configure git and tag branch
          command: |
            .circleci/push_git_tag.sh
  deploy_prod:
    docker:
      - image: circleci/python:3.7
        environment:
            TZ: "/usr/share/zoneinfo/America/New_York"
    steps:
      - checkout
      - deploy:
          command: |
            cat ./node_config >> ~/.ssh/config
            bash ./ecs_deploy.sh master prod
workflows:
  version: 2
  trigger:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows
  initial_flow:
    when: << pipeline.parameters.requirements >>
    jobs:
      - build_test
      - build_img:
          filters:
            branches:
              only:
                - /^docker-.*/
                - develop
                - staging
                - master
      - deploy_prod:
          filters:
            branches:
              only: master
          requires:
            - build_test
            - build_img