##################
### config.yml ###
##################

version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.6
        steps:
            - checkout
            - run:
                command: |
                    source .circleci/commit_check.sh
workflows:
  version: 2
  default-workflow:
    jobs:
    - build:
        filters:
            branches:
                only:
                    - master